# Generated by Django 5.1.2 on 2024-10-25 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0017_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitymodel',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_ledger.firm'),
        ),
    ]
